2023-01-23 11:17:07,230 ERROR: Exception on /user/Cassiano [GET] [in /Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/cassiano/code/Python/flask_tutorial/app/routes.py", line 69, in user
    form = EmptyForm()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/cassiano/code/Python/flask_tutorial/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
  File "/Users/cassiano/code/Python/flask_tutorial/app/templates/base.html", line 29, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "/Users/cassiano/code/Python/flask_tutorial/app/templates/user.html", line 12, in block 'content'
    {% elif not current_user.is_following(user) %}
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'follwers'
2023-01-23 11:17:53,701 INFO: Microblog startup [in /Users/cassiano/code/Python/flask_tutorial/app/__init__.py:41]
2023-01-23 11:18:06,561 INFO: Microblog startup [in /Users/cassiano/code/Python/flask_tutorial/app/__init__.py:41]
2023-01-24 08:02:21,543 INFO: Microblog startup [in /Users/cassiano/code/Python/flask_tutorial/app/__init__.py:41]
2023-01-24 08:11:15,082 ERROR: Exception on / [GET] [in /Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/cassiano/code/Python/flask_tutorial/app/routes.py", line 21, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/cassiano/code/Python/flask_tutorial/app/templates/index.html", line 10, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2023-01-24 08:11:18,247 ERROR: Exception on /index [GET] [in /Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/cassiano/code/Python/flask_tutorial/app/routes.py", line 21, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/cassiano/code/Python/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/cassiano/code/Python/flask_tutorial/app/templates/index.html", line 10, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
